AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - ?.rb

require:
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle: table

Lint/AmbiguousOperatorPrecedence: { Enabled: false }

Metrics/AbcSize:              { Enabled: false }
Metrics/BlockLength:          { Enabled: false }
Metrics/BlockNesting:         { Enabled: false }
Metrics/ClassLength:          { Enabled: false }
Metrics/CyclomaticComplexity: { Enabled: false }
Metrics/MethodLength:         { Enabled: false }
Metrics/ModuleLength:         { Enabled: false }
Metrics/PerceivedComplexity:  { Enabled: false }

Naming/MethodParameterName:   { Enabled: false }

RSpec/ExampleLength:          { Enabled: false }
RSpec/MultipleExpectations:   { Enabled: false }

Style/CommentedKeyword:       { Enabled: false }
Style/Documentation:          { Enabled: false }
Style/FormatStringToken:      { Enabled: false }
Style/MinMaxComparison:       { Enabled: false }
Style/NegatedIfElseCondition: { Enabled: false }
Style/NumericPredicate:       { Enabled: false }
Style/ParallelAssignment:     { Enabled: false }
Style/StringLiterals:         { EnforcedStyle: double_quotes }
Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/TrailingCommaInHashLiteral:    { EnforcedStyleForMultiline: consistent_comma }
